#  RCP

In [3]:
%matplotlib inline
%reload_ext autoreload
%autoreload 2

In [7]:
from fastai.structured import *
from fastai.column_data import *
np.set_printoptions(threshold=50, edgeitems=20)

PATH='../../../fastai/data/'

In [8]:
!ls ../../../fastai/data//

reason_code


## Create datasets

In [16]:
def concat_csvs(dirname):
    path = f'{PATH}{dirname}'
    filenames=glob(f"{PATH}/*.csv")

    wrote_header = False
    with open(f"{path}.csv","w") as outputfile:
        for filename in filenames:
            name = filename.split(".")[0]
            with open(filename) as f:
                line = f.readline()
                if not wrote_header:
                    wrote_header = True
                    outputfile.write("file,"+line)
                for line in f:
                     outputfile.write(name + "," + line)
                outputfile.write("\n")

In [17]:
# concat_csvs('googletrend')
# concat_csvs('weather')

Feature Space:
* train: Training set provided by competition
* store: List of stores
* store_states: mapping of store to the German state they are in
* List of German state names
* googletrend: trend of certain google keywords over time, found by users to correlate well w/ given data
* weather: weather
* test: testing set

In [202]:
table_names = ['train','test']

We'll be using the popular data manipulation framework `pandas`. Among other things, pandas allows you to manipulate tables/data frames in python as one would in a database.

We're going to go ahead and load all of our csv's as dataframes into the list `tables`.

In [203]:
tables = [pd.read_csv(f'{PATH}{fname}.csv', low_memory=False) for fname in table_names]

In [204]:
from IPython.display import HTML

We can use `head()` to get a quick look at the contents of each table:
* train: Contains store information on a daily basis, tracks things like sales, customers, whether that day was a holdiay, etc.
* store: general info about the store including competition, etc.
* store_states: maps store to state it is in
* state_names: Maps state abbreviations to names
* googletrend: trend data for particular week/state
* weather: weather conditions for each state
* test: Same as training table, w/o sales and customers


In [205]:
for t in tables: display(t.head())

Feature1  Feature2  Feature3  Feature4  reason_id
0      2219   1768599        67         1        102
1      2219   1768599        67         1        102
2      2219   1768599        67         1        102
3      2219   1768599        67         1        102
4      2219   1768599        67         1        102

Feature1  Feature2  Feature3  Feature4  reason_id
0       893   1754095        21         3         80
1       893   1754095        21         3         80
2       893   1754095        21         3         80
3       893   1754095        21         3         80
4       893   1754095        21         3         80

This is very representative of a typical industry dataset.

The following returns summarized aggregate information to each table accross each field.

In [206]:
# for t in tables: display(DataFrameSummary(t).summary())

## Data Cleaning / Feature Engineering

As a structured data problem, we necessarily have to go through all the cleaning and feature engineering, even though we're using a neural network.

In [248]:
train,  test = tables

In [249]:
df = train

In [250]:
len(train),len(test)

(110090, 40452)

We turn state Holidays to booleans, to make them more convenient for modeling. We can do calculations on pandas fields using notation very similar (often identical) to numpy.

In [251]:
# train.StateHoliday = train.StateHoliday!='0'
# test.StateHoliday = test.StateHoliday!='0'

`join_df` is a function for joining tables on specific fields. By default, we'll be doing a left outer join of `right` on the `left` argument using the given fields for each table.

Pandas does joins using the `merge` method. The `suffixes` argument describes the naming convention for duplicate fields. We've elected to leave the duplicate field names on the left untouched, and append a "\_y" to those on the right.

In [252]:
# def join_df(left, right, left_on, right_on=None, suffix='_y'):
#     if right_on is None: right_on = left_on
#     return left.merge(right, how='left', left_on=left_on, right_on=right_on, 
#                       suffixes=("", suffix))

Join weather/state names.

In [253]:
# weather = join_df(weather, state_names, "file", "StateName")

In pandas you can add new columns to a dataframe by simply defining it. We'll do this for googletrends by extracting dates and state names from the given data and adding those columns.

We're also going to replace all instances of state name 'NI' to match the usage in the rest of the data: 'HB,NI'. This is a good opportunity to highlight pandas indexing. We can use `.loc[rows, cols]` to select a list of rows and a list of columns from the dataframe. In this case, we're selecting rows w/ statename 'NI' by using a boolean list `googletrend.State=='NI'` and selecting "State".

In [254]:
# googletrend['Date'] = googletrend.week.str.split(' - ', expand=True)[0]
# googletrend['State'] = googletrend.file.str.split('_', expand=True)[2]
# googletrend.loc[googletrend.State=='NI', "State"] = 'HB,NI'

The following extracts particular date fields from a complete datetime for the purpose of constructing categoricals.

You should *always* consider this feature extraction step when working with date-time. Without expanding your date-time into these additional fields, you can't capture any trend/cyclical behavior as a function of time at any of these granularities. We'll add to every table with a date field.

In [255]:
# add_datepart(weather, "Date", drop=False)
# add_datepart(googletrend, "Date", drop=False)
# add_datepart(train, "Date", drop=False)
# add_datepart(test, "Date", drop=False)

The Google trends data has a special category for the whole of the Germany - we'll pull that out so we can use it explicitly.

In [256]:
# trend_de = googletrend[googletrend.file == 'Rossmann_DE']

Now we can outer join all of our data into a single dataframe. Recall that in outer joins everytime a value in the joining field on the left table does not have a corresponding value on the right table, the corresponding row in the new table has Null values for all right table fields. One way to check that all records are consistent and complete is to check for Null values post-join, as we do here.

*Aside*: Why note just do an inner join?
If you are assuming that all records are complete and match on the field you desire, an inner join will do the same thing as an outer join. However, in the event you are wrong or a mistake is made, an outer join followed by a null-check will catch it. (Comparing before/after # of rows for inner join is equivalent, but requires keeping track of before/after row #'s. Outer join is easier.)

In [257]:
# store = join_df(store, store_states, "Store")
# len(store[store.State.isnull()])

In [258]:
# joined = join_df(train, store, "Store")
# joined_test = join_df(test, store, "Store")
# len(joined[joined.StoreType.isnull()]),len(joined_test[joined_test.StoreType.isnull()])

In [259]:
# joined = join_df(joined, googletrend, ["State","Year", "Week"])
# joined_test = join_df(joined_test, googletrend, ["State","Year", "Week"])
# len(joined[joined.trend.isnull()]),len(joined_test[joined_test.trend.isnull()])

In [260]:
# joined = joined.merge(trend_de, 'left', ["Year", "Week"], suffixes=('', '_DE'))
# joined_test = joined_test.merge(trend_de, 'left', ["Year", "Week"], suffixes=('', '_DE'))
# len(joined[joined.trend_DE.isnull()]),len(joined_test[joined_test.trend_DE.isnull()])

In [261]:
# joined = join_df(joined, weather, ["State","Date"])
# joined_test = join_df(joined_test, weather, ["State","Date"])
# len(joined[joined.Mean_TemperatureC.isnull()]),len(joined_test[joined_test.Mean_TemperatureC.isnull()])

In [262]:
# for df in (joined, joined_test):
#     for c in df.columns:
#         if c.endswith('_y'):
#             if c in df.columns: df.drop(c, inplace=True, axis=1)

Next we'll fill in missing values to avoid complications with `NA`'s. `NA` (not available) is how Pandas indicates missing values; many models have problems when missing values are present, so it's always important to think about how to deal with them. In these cases, we are picking an arbitrary *signal value* that doesn't otherwise appear in the data.

In [263]:
# for df in (joined,joined_test):
#     df['CompetitionOpenSinceYear'] = df.CompetitionOpenSinceYear.fillna(1900).astype(np.int32)
#     df['CompetitionOpenSinceMonth'] = df.CompetitionOpenSinceMonth.fillna(1).astype(np.int32)
#     df['Promo2SinceYear'] = df.Promo2SinceYear.fillna(1900).astype(np.int32)
#     df['Promo2SinceWeek'] = df.Promo2SinceWeek.fillna(1).astype(np.int32)

Next we'll extract features "CompetitionOpenSince" and "CompetitionDaysOpen". Note the use of `apply()` in mapping a function across dataframe values.

In [264]:
# for df in (joined,joined_test):
#     df["CompetitionOpenSince"] = pd.to_datetime(dict(year=df.CompetitionOpenSinceYear, 
#                                                      month=df.CompetitionOpenSinceMonth, day=15))
#     df["CompetitionDaysOpen"] = df.Date.subtract(df.CompetitionOpenSince).dt.days

We'll replace some erroneous / outlying data.

In [265]:
# for df in (joined,joined_test):
#     df.loc[df.CompetitionDaysOpen<0, "CompetitionDaysOpen"] = 0
#     df.loc[df.CompetitionOpenSinceYear<1990, "CompetitionDaysOpen"] = 0

We add "CompetitionMonthsOpen" field, limiting the maximum to 2 years to limit number of unique categories.

In [266]:
# for df in (joined,joined_test):
#     df["CompetitionMonthsOpen"] = df["CompetitionDaysOpen"]//30
#     df.loc[df.CompetitionMonthsOpen>24, "CompetitionMonthsOpen"] = 24
# joined.CompetitionMonthsOpen.unique()

Same process for Promo dates.

In [267]:
# for df in (joined,joined_test):
#     df["Promo2Since"] = pd.to_datetime(df.apply(lambda x: Week(
#         x.Promo2SinceYear, x.Promo2SinceWeek).monday(), axis=1).astype(pd.datetime))
#     df["Promo2Days"] = df.Date.subtract(df["Promo2Since"]).dt.days

In [268]:
# for df in (joined,joined_test):
#     df.loc[df.Promo2Days<0, "Promo2Days"] = 0
#     df.loc[df.Promo2SinceYear<1990, "Promo2Days"] = 0
#     df["Promo2Weeks"] = df["Promo2Days"]//7
#     df.loc[df.Promo2Weeks<0, "Promo2Weeks"] = 0
#     df.loc[df.Promo2Weeks>25, "Promo2Weeks"] = 25
#     df.Promo2Weeks.unique()

In [269]:
# joined.to_feather(f'{PATH}joined')
# joined_test.to_feather(f'{PATH}joined_test')

## Durations

It is common when working with time series data to extract data that explains relationships across rows as opposed to columns, e.g.:
* Running averages
* Time until next event
* Time since last event

This is often difficult to do with most table manipulation frameworks, since they are designed to work with relationships across columns. As such, we've created a class to handle this type of data.

We'll define a function `get_elapsed` for cumulative counting across a sorted dataframe. Given a particular field `fld` to monitor, this function will start tracking time since the last occurrence of that field. When the field is seen again, the counter is set to zero.

Upon initialization, this will result in datetime na's until the field is encountered. This is reset every time a new store is seen. We'll see how to use this shortly.

In [270]:
# def get_elapsed(fld, pre):
#     day1 = np.timedelta64(1, 'D')
#     last_date = np.datetime64()
#     last_store = 0
#     res = []

#     for s,v,d in zip(df.Store.values,df[fld].values, df.Date.values):
#         if s != last_store:
#             last_date = np.datetime64()
#             last_store = s
#         if v: last_date = d
#         res.append(((d-last_date).astype('timedelta64[D]') / day1))
#     df[pre+fld] = res

We'll be applying this to a subset of columns:

In [271]:
# columns = ["Date", "Store", "Promo", "StateHoliday", "SchoolHoliday"]

In [272]:
# df = train[columns]

In [273]:
# df = test[columns]

Let's walk through an example.

Say we're looking at School Holiday. We'll first sort by Store, then Date, and then call `add_elapsed('SchoolHoliday', 'After')`:
This will apply to each row with School Holiday:
* A applied to every row of the dataframe in order of store and date
* Will add to the dataframe the days since seeing a School Holiday
* If we sort in the other direction, this will count the days until another holiday.

In [274]:
# fld = 'SchoolHoliday'
# df = df.sort_values(['Store', 'Date'])
# get_elapsed(fld, 'After')
# df = df.sort_values(['Store', 'Date'], ascending=[True, False])
# get_elapsed(fld, 'Before')

We'll do this for two more fields.

In [275]:
# fld = 'StateHoliday'
# df = df.sort_values(['Store', 'Date'])
# get_elapsed(fld, 'After')
# df = df.sort_values(['Store', 'Date'], ascending=[True, False])
# get_elapsed(fld, 'Before')

In [276]:
# fld = 'Promo'
# df = df.sort_values(['Store', 'Date'])
# get_elapsed(fld, 'After')
# df = df.sort_values(['Store', 'Date'], ascending=[True, False])
# get_elapsed(fld, 'Before')

We're going to set the active index to Date.

In [277]:
# df = df.set_index("Date")

Then set null values from elapsed field calculations to 0.

In [278]:
# columns = ['SchoolHoliday', 'StateHoliday', 'Promo']

In [279]:
# for o in ['Before', 'After']:
#     for p in columns:
#         a = o+p
#         df[a] = df[a].fillna(0).astype(int)

Next we'll demonstrate window functions in pandas to calculate rolling quantities.

Here we're sorting by date (`sort_index()`) and counting the number of events of interest (`sum()`) defined in `columns` in the following week (`rolling()`), grouped by Store (`groupby()`). We do the same in the opposite direction.

In [280]:
# bwd = df[['Store']+columns].sort_index().groupby("Store").rolling(7, min_periods=1).sum()

In [281]:
# fwd = df[['Store']+columns].sort_index(ascending=False
#                                       ).groupby("Store").rolling(7, min_periods=1).sum()

Next we want to drop the Store indices grouped together in the window function.

Often in pandas, there is an option to do this in place. This is time and memory efficient when working with large datasets.

In [282]:
# bwd.drop('Store',1,inplace=True)
# bwd.reset_index(inplace=True)

In [283]:
# fwd.drop('Store',1,inplace=True)
# fwd.reset_index(inplace=True)

In [284]:
# df.reset_index(inplace=True)

Now we'll merge these values onto the df.

In [285]:
# df = df.merge(bwd, 'left', ['Date', 'Store'], suffixes=['', '_bw'])
# df = df.merge(fwd, 'left', ['Date', 'Store'], suffixes=['', '_fw'])

In [286]:
# df.drop(columns,1,inplace=True)

In [313]:
##Adding a dummy continuous variable as it expects atleast one continuous variable.

df["Dummy"] =1

In [314]:
df.head()

Feature1 Feature2 Feature3 Feature4  reason_id  Dummy
0     2219  1768599       67        1        102      1
1     2219  1768599       67        1        102      1
2     2219  1768599       67        1        102      1
3     2219  1768599       67        1        102      1
4     2219  1768599       67        1        102      1

It's usually a good idea to back up large tables of extracted / wrangled features before you join them onto another one, that way you can go back to it easily if you need to make changes to it.

In [245]:
df.to_feather(f'{PATH}df3')

In [246]:
df = pd.read_feather(f'{PATH}df3')

In [241]:
# df["Date"] = pd.to_datetime(df.Date)

In [288]:
df.head()

Feature1  Feature2  Feature3  Feature4  reason_id
0      2219   1768599        67         1        102
1      2219   1768599        67         1        102
2      2219   1768599        67         1        102
3      2219   1768599        67         1        102
4      2219   1768599        67         1        102

In [289]:
df.columns

Index(['Feature1', 'Feature2', 'Feature3', 'Feature4', 'reason_id'], dtype='object')

In [290]:
# joined = join_df(joined, df, ['Store', 'Date'])

In [291]:
# joined_test = join_df(joined_test, df, ['Store', 'Date'])

The authors also removed all instances where the store had zero sale / was closed. We speculate that this may have cost them a higher standing in the competition. One reason this may be the case is that a little exploratory data analysis reveals that there are often periods where stores are closed, typically for refurbishment. Before and after these periods, there are naturally spikes in sales that one might expect. By ommitting this data from their training, the authors gave up the ability to leverage information about these periods to predict this otherwise volatile behavior.

In [292]:
# joined = joined[joined.Sales!=0]

We'll back this up as well.

In [293]:
# joined.reset_index(inplace=True)
# joined_test.reset_index(inplace=True)

In [294]:
# joined.to_feather(f'{PATH}joined')
# joined_test.to_feather(f'{PATH}joined_test')

We now have our final set of engineered features.

While these steps were explicitly outlined in the paper, these are all fairly typical feature engineering steps for dealing with time series data and are practical in any similar setting.

## Create features

In [295]:
# joined = pd.read_feather(f'{PATH}joined')
# joined_test = pd.read_feather(f'{PATH}joined_test')

In [296]:
# joined.head().T.head(40)

Now that we've engineered all our features, we need to convert to input compatible with a neural network.

This includes converting categorical variables into contiguous integers or one-hot encodings, normalizing continuous features to standard normal, etc...

In [315]:
cat_vars = ['Feature1','Feature2', 'Feature3','Feature4']

contin_vars = ['Dummy']

n = len(df); n

110090

In [316]:
# dep = 'Sales'
# joined = joined[cat_vars+contin_vars+[dep, 'Date']].copy()

In [317]:
# joined_test[dep] = 0
# joined_test = joined_test[cat_vars+contin_vars+[dep, 'Date', 'Id']].copy()

In [360]:
for v in cat_vars: df[v] = df[v].astype('category').cat.as_ordered()

In [319]:
# for v in cat_vars: joined[v] = joined[v].astype('category').cat.as_ordered()

In [320]:
# apply_cats(joined_test, joined)

In [321]:
# for v in contin_vars:
#     joined[v] = joined[v].fillna(0).astype('float32')
#     joined_test[v] = joined_test[v].fillna(0).astype('float32')

We're going to run on a sample.

In [342]:
idxs = get_cv_idxs(n, val_pct=150000/n)
joined_samp = df.iloc[idxs].set_index("Feature1")
samp_size = len(joined_samp); samp_size

110090

To run on the full dataset, use this instead:

In [344]:
samp_size = n
joined_samp = df.set_index("Feature1")

We can now process our data...

In [345]:
joined_samp.head(2)

Feature2  Feature3  Feature4  Dummy
Feature1                                     
158             13        33         1    0.0
158             13        33         1    0.0

In [326]:
df, y, nas, mapper = proc_df(df, 'reason_id', do_scale=True)
yl = np.log(y)

In [327]:
# joined_test = joined_test.set_index("Date")

In [328]:
# df_test, _, nas, mapper = proc_df(joined_test, 'Sales', do_scale=True, skip_flds=['Id'],
#                                   mapper=mapper, na_dict=nas)

In [347]:
df.head(2)

Feature1  Feature2  Feature3  Feature4  Dummy
0       158        13        33         1    0.0
1       158        13        33         1    0.0

In time series data, cross-validation is not random. Instead, our holdout data is generally the most recent data, as it would be in real application. This issue is discussed in detail in [this post](http://www.fast.ai/2017/11/13/validation-sets/) on our web site.

One approach is to take the last 25% of rows (sorted by date) as our validation set.

In [348]:
train_ratio = 0.75
# train_ratio = 0.9
train_size = int(samp_size * train_ratio); train_size
val_idx = list(range(train_size, len(df)))

An even better option for picking a validation set is using the exact same length of time period as the test set uses - this is implemented here:

In [349]:
df.index

RangeIndex(start=0, stop=110090, step=1)

In [350]:
val_idx = np.flatnonzero(df.index>=100000)

In [351]:
val_idx

array([100000, 100001, 100002, 100003, 100004, 100005, 100006, 100007, 100008, 100009, 100010, 100011,
       100012, 100013, 100014, 100015, 100016, 100017, 100018, 100019, ..., 110070, 110071, 110072, 110073,
       110074, 110075, 110076, 110077, 110078, 110079, 110080, 110081, 110082, 110083, 110084, 110085,
       110086, 110087, 110088, 110089], dtype=int64)

## DL

We're ready to put together our models.

Root-mean-squared percent error is the metric Kaggle used for this competition.

In [352]:
def inv_y(a): return np.exp(a)

def exp_rmspe(y_pred, targ):
    targ = inv_y(targ)
    pct_var = (targ - inv_y(y_pred))/targ
    return math.sqrt((pct_var**2).mean())

max_log_y = np.max(yl)
y_range = (0, max_log_y*1.2)

We can create a ModelData object directly from out data frame.

In [79]:
??ColumnarModelData.from_data_frame

In [353]:
md = ColumnarModelData.from_data_frame(PATH, val_idx, df, yl.astype(np.float32), cat_flds=cat_vars, bs=128,
                                       test_df=test)

Some categorical variables have a lot more levels than others. Store, in particular, has over a thousand!

In [362]:
cat_sz = [(c, len(df[c].cat.categories)+1) for c in cat_vars]

In [363]:
cat_sz

[('Feature1', 348), ('Feature2', 44), ('Feature3', 47), ('Feature4', 5)]

We use the *cardinality* of each variable (that is, its number of unique values) to decide how large to make its *embeddings*. Each level will be associated with a vector with length defined as below.

In [364]:
emb_szs = [(c, min(50, (c+1)//2)) for _,c in cat_sz]

In [365]:
emb_szs

[(348, 50), (44, 22), (47, 24), (5, 3)]

In [6]:
m = md.get_learner(emb_szs, len(df.columns)-len(cat_vars),
                   0.04, 1, [1000,500], [0.001,0.01], y_range=y_range)
lr = 1e-3

NameError: name 'md' is not defined

In [4]:
x=torch.rand(3,4)
y=torch.rand(3,4)
x=x.cuda()
y=y.cuda()
x+y

C:\Users\khabiya\AppData\Local\Continuum\anaconda3\envs\fastai\lib\site-packages\torch\cuda\__init__.py:116: UserWarning: 
    Found GPU0 Quadro K1200 which is of cuda capability 5.0.
    PyTorch no longer supports this GPU because it is too old.
    
  warnings.warn(old_gpu_warn % (d, name, major, capability[1]))


RuntimeError: cuda runtime error (48) : no kernel image is available for execution on the device at c:\anaconda2\conda-bld\pytorch_1519501749874\work\torch\lib\thc\generic/THCTensorMathPointwise.cu:301

In [5]:
m.lr_find()

NameError: name 'm' is not defined

In [ ]:
m.sched.plot(100)

### Sample

In [201]:
m = md.get_learner(emb_szs, len(df.columns)-len(cat_vars),
                   0.04, 1, [1000,500], [0.001,0.01], y_range=y_range)
lr = 1e-3

In [64]:
m.fit(lr, 3, metrics=[exp_rmspe])

A Jupyter Widget

[ 0.       0.02479  0.02205  0.19309]                          
[ 1.       0.02044  0.01751  0.18301]                          
[ 2.       0.01598  0.01571  0.17248]                          



In [65]:
m.fit(lr, 5, metrics=[exp_rmspe], cycle_len=1)

A Jupyter Widget

[ 0.       0.01258  0.01278  0.16   ]                          
[ 1.       0.01147  0.01214  0.15758]                          
[ 2.       0.01157  0.01157  0.15585]                          
[ 3.       0.00984  0.01124  0.15251]                           
[ 4.       0.00946  0.01094  0.15197]                           



In [66]:
m.fit(lr, 2, metrics=[exp_rmspe], cycle_len=4)

A Jupyter Widget

[ 0.       0.01179  0.01242  0.15512]                           
[ 1.       0.00921  0.01098  0.15003]                           
[ 2.       0.00771  0.01031  0.14431]                           
[ 3.       0.00632  0.01016  0.14358]                           
[ 4.       0.01003  0.01305  0.16574]                           
[ 5.       0.00827  0.01087  0.14937]                           
[ 6.       0.00628  0.01025  0.14506]                           
[ 7.       0.0053   0.01     0.14449]                           



### All

In [94]:
m = md.get_learner(emb_szs, len(df.columns)-len(cat_vars),
                   0.04, 1, [1000,500], [0.001,0.01], y_range=y_range)
lr = 1e-3

In [95]:
m.fit(lr, 1, metrics=[exp_rmspe])

A Jupyter Widget

[ 0.       0.01456  0.01544  0.1148 ]                            



In [93]:
m.fit(lr, 3, metrics=[exp_rmspe])

HBox(children=(IntProgress(value=0, description='Epoch', max=3), HTML(value='')))

[ 0.       0.01418  0.02066  0.12765]                           
[ 1.       0.01081  0.01276  0.11221]                           
[ 2.       0.00976  0.01233  0.10987]                            



In [94]:
m.fit(lr, 3, metrics=[exp_rmspe], cycle_len=1)

HBox(children=(IntProgress(value=0, description='Epoch', max=3), HTML(value='')))

[ 0.       0.00801  0.01081  0.09899]                            
[ 1.       0.00714  0.01083  0.09846]                            
[ 2.       0.00707  0.01088  0.09878]                            



### Test

In [185]:
m = md.get_learner(emb_szs, len(df.columns)-len(cat_vars),
                   0.04, 1, [1000,500], [0.001,0.01], y_range=y_range)
lr = 1e-3

In [102]:
m.fit(lr, 3, metrics=[exp_rmspe])

HBox(children=(IntProgress(value=0, description='Epoch', max=3), HTML(value='')))

[ 0.       0.01413  0.0063   0.07628]                           
[ 1.       0.01022  0.00859  0.08851]                           
[ 2.       0.00932  0.00001  0.00243]                            



In [103]:
m.fit(lr, 3, metrics=[exp_rmspe], cycle_len=1)

HBox(children=(IntProgress(value=0, description='Epoch', max=3), HTML(value='')))

[ 0.       0.00748  0.       0.00167]                            
[ 1.       0.00717  0.00009  0.00947]                            
[ 2.       0.00643  0.00013  0.01147]                            



In [105]:
m.save('val0')

In [186]:
m.load('val0')

In [187]:
x,y=m.predict_with_targs()

In [188]:
exp_rmspe(x,y)

0.01147316926177568

In [189]:
pred_test=m.predict(True)

In [190]:
pred_test = np.exp(pred_test)

In [192]:
joined_test['Sales']=pred_test

In [193]:
csv_fn=f'{PATH}tmp/sub.csv'

In [200]:
joined_test[['Id','Sales']].to_csv(csv_fn, index=False)

In [202]:
FileLink(csv_fn)

/home/ubuntu/fastai/courses/dl1/data/rossmann/tmp/sub.csv

## RF

In [152]:
from sklearn.ensemble import RandomForestRegressor

In [157]:
from sklearn.ensemble import RandomForestClassifier

In [181]:
df2 = df.drop(['reason_id'], axis = 1, inplace = False)

In [182]:
((val,trn), (y_val,y_trn)) = split_by_idx(val_idx, df2.values, yl)

In [184]:
m = RandomForestClassifier(n_estimators=40, max_features=0.99, min_samples_leaf=2,
                          n_jobs=-1, oob_score=True)
m.fit(trn, y_trn);

In [185]:
preds = m.predict(val)
m.score(trn, y_trn), m.score(val, y_val), m.oob_score_

(0.94726, 0.9323092170465808, 0.9448)

In [188]:
val.size

40360

In [197]:
arr = np.array([[2927,2769237,14,4]])

In [198]:
m.predict(arr)

array([37], dtype=int64)